version: "3.3"

services:
  traefik:
    image: "traefik"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: "bind"
        source: "./traefik.yaml"
        target: "/etc/traefik/traefik.yaml"
      - type: "bind"
        source: "./acme.json"
        target: "/acme.json"
    networks:
      - "mynetwork"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    ports:
      - "8080:80"
    networks:
      - "mynetwork"

networks:
  mynetwork:
