version: "3.3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik"
    entrypoint: "traefik"
    command:
      - "--configfile"
      - "/traefik.yaml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: "bind"
        source: "./traefik.yaml"
        target: "/traefik.yaml"
      - type: "bind"
        source: "./acme.json"
        target: "/acme.json"
    networks:
      - "mynetwork"

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    ports:
      - "8080:80"
    networks:
      - "mynetwork"

networks:
  mynetwork:
