global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL

accessLog: true

providers:
  file:
    directory: "/etc/traefik"

api:
  insecure: true  # Don't do this in production!

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

http:
  routers:
    whoami:
      rule: "Host(`sandbox.matthewdavis.io`) && Path(`/`)"
      entryPoints:
        - web
      service: whoami
      tls:
        certResolver: myresolver
        domains:
          - main: sandbox.matthewdavis.io
      middlewares:
        - redirect-to-https
  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:8080
  middlewares:
    redirect-to-https:
      redirectscheme:
        scheme: websecure
        permanent: true

certificatesResolvers:
  myresolver:
    acme:
      email: matthew@matthewdavis.io
#      caServer = "https://acme-v02.api.letsencrypt.org/directory"
      storage: /acme.json
      tlsChallenge: {}

